spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
    url: jdbc:h2:mem://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    # show_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace